const { Router } = require("express");
const { register, login, googleLogin, logout, me, forgotPassword, resetPassword } = require("../controllers/auth.controller");
const { authenticate } = require("../middleware/auth.middleware");
const router = Router();
router.post("/register", register);
router.post("/login", login);
router.post("/google", googleLogin);
router.post("/logout", logout);
router.post("/forgot-password", forgotPassword);
router.post("/reset-password", resetPassword);
router.get("/me", authenticate, me);
module.exports = router;