const { Router } = require("express");
const { getMemberships, createMembership, getPlans, getMembershipById } = require("../controllers/membership.controller");
const { authenticate, requireAdminOrStaff } = require("../middleware/auth.middleware");
const router = Router();
router.use(authenticate, requireAdminOrStaff);
router.get("/plans", getPlans);
router.get("/", getMemberships);
router.get("/:id", getMembershipById);
router.post("/", createMembership);
module.exports = router;