const { Router } = require("express");
const { getStaff, createStaff, getStaffPermissions, updateStaffPermissions } = require("../controllers/staff.controller");
const { authenticate, requireOwner } = require("../middleware/auth.middleware");
const router = Router();
router.use(authenticate, requireOwner);
router.get("/", getStaff);
router.post("/", createStaff);
router.get("/:id/permissions", getStaffPermissions);
router.patch("/:id/permissions", updateStaffPermissions);
module.exports = router;